version: '2'
services:
  prestashop:
    image: prestashop/prestashop
    ports:
      - "8002:80"
    volumes:
      - /var/www/html
      - ./:/var/www/html/modules/axxell-recommendations
    environment:
      - DB_SERVER=mysql
      - DB_USER=root
      - DB_PASSWD=root
      - DB_NAME=prestashop
      - PS_INSTALL_AUTO=1
      - PS_HANDLE_DYNAMIC_DOMAIN=1
    links:
      - mysql
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop
