<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Axxell
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace Axxell\Api;

use \Axxell\Configuration;
use \Axxell\ApiClient;
use \Axxell\ApiException;
use \Axxell\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Axxell
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for aggregateCountEvents
     *
     * 
     *
     */
    public function test_aggregateCountEvents() {

    }
    
    /**
     * Test case for aggregateEffective
     *
     * 
     *
     */
    public function test_aggregateEffective() {

    }
    
    /**
     * Test case for aggregateEvents
     *
     * 
     *
     */
    public function test_aggregateEvents() {

    }
    
    /**
     * Test case for aggregateRecent
     *
     * 
     *
     */
    public function test_aggregateRecent() {

    }
    
    /**
     * Test case for aggregateTop
     *
     * 
     *
     */
    public function test_aggregateTop() {

    }
    
    /**
     * Test case for authStore
     *
     * 
     *
     */
    public function test_authStore() {

    }
    
    /**
     * Test case for retrieveEvents
     *
     * 
     *
     */
    public function test_retrieveEvents() {

    }
    
    /**
     * Test case for registerEvent
     *
     * 
     *
     */
    public function test_registerEvent() {

    }
    
    /**
     * Test case for deleteAllEvents
     *
     * 
     *
     */
    public function test_deleteAllEvents() {

    }
    
    /**
     * Test case for retrieveItems
     *
     * 
     *
     */
    public function test_retrieveItems() {

    }
    
    /**
     * Test case for registerItem
     *
     * 
     *
     */
    public function test_registerItem() {

    }
    
    /**
     * Test case for deleteAllItems
     *
     * 
     *
     */
    public function test_deleteAllItems() {

    }
    
    /**
     * Test case for deleteItem
     *
     * 
     *
     */
    public function test_deleteItem() {

    }
    
    /**
     * Test case for recommendInteresting
     *
     * 
     *
     */
    public function test_recommendInteresting() {

    }
    
    /**
     * Test case for recommendSimilar
     *
     * 
     *
     */
    public function test_recommendSimilar() {

    }
    
    /**
     * Test case for registerStore
     *
     * 
     *
     */
    public function test_registerStore() {

    }
    
}
